# Generated by Django 4.1.4 on 2023-01-31 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bullHornId", models.FloatField(null=True)),
                ("nameCandidate", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("subjectName", models.CharField(max_length=100)),
                ("scoreAssessmentTotal", models.FloatField(null=True)),
                ("client", models.CharField(max_length=100)),
                ("percentile", models.FloatField()),
                ("subjectCoverageTotal", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namePractice", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameSubject", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practiceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadFile.practice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameSubSkill", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subjectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadFile.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weak", models.IntegerField()),
                ("proficient", models.IntegerField()),
                ("strong", models.IntegerField()),
                ("workSpeedAccuracy", models.CharField(max_length=100)),
                ("applicationAbility", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadFile.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadFile.candidate",
                    ),
                ),
                (
                    "subjectSkillId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadFile.subjectskills",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="SubjectUserAccount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="uploadFile.subject"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
