# Generated by Django 4.1.4 on 2022-12-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASSIGNMENT_DONE',
        ),
    ]
